kind: Pod
apiVersion: v1 
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: Practice
        value: Devops
      - name: duration
        value: 120hrs